#Simulación de creación de Usuarios
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('anjudark89','Flor Nallely', 'Flores', 'Vicente', 'M', 22, 'anjudark@xanum.uam.mx', '123456', 1, 2, null, 1, 6, null, null, '51f824440a000', 1, '2013-09-01');
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('luisa.207310034','Luisa Maria', 'Gomez', 'Leyva', 'M', 23, 'luisa.207310034@xanum.uam.mx', '123456', 3, 2, null, 1, 5, null, null, '51f82452e4085', 1, '2013-09-01');
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('jcesarcbi','Julio Cesar', 'Padilla', 'Dorantes', 'H', 28, 'jcesarcbi@xanum.uam.mx', '123456', 2, 2, null, 1, 9, null, null, '51f8245ed0b24', 1, '2013-09-01');
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('guillermotorres','Guillermo', 'Torres', 'Lopez', 'H', 29, 'guillermotorres@xanum.uam.mx', '123456', 2, 2, null, 1, 7, null, null, '51f82467002fe', 1, '2013-09-01');
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('jezrelmx1304','Efren', 'Valdez', 'Jasso', 'H', 30, 'jezrelmx1304@xanum.uam.mx', '123456', 4, 2, null, 1, 10, null, null, '51f82470ceef0', 1, '2013-09-01');
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsuario, idDivision, idGradoPosgrado, idGradoActivo, idAvatar, cargo, area, codigoActivacion, estatus, fechaRegistro) VALUES ('virtu@mi','Coordinación', 'Educación', 'Virtual', 'H', 30, 'ludico@virtuami.izt.uam.mx', '123456', 4, 2, null, 1, 10, null, null, '5220a414ab0b3', 1, '2013-09-01');

#Simulación de creación de Jugadores
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (1,1,7767000);
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (2,1,7506000);
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (3,1,7696000);
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (4,1,7224000);
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (5,1,7155000);
INSERT INTO loteriadb.jugador (idUsr, idJuego, scoreTotal) VALUES (6,1,7371000);