INSERT loteriadb.frase (frase, idFrase) VALUES ('Like the legend of the phoenix All ends with beginnings What keeps the planet spinning The force from the beginning ',1);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''ve come too far To give up who we are So let''s raise the bar And our cups to the stars',2);
INSERT loteriadb.frase (frase, idFrase) VALUES ('She''s up all night to the sun I''m up all night to get some She''s up all night for good fun I''m up all night to get lucky',3);
INSERT loteriadb.frase (frase, idFrase) VALUES ('The present has no ribbon Your gift keeps on giving What is this I''m feeling If you want to leave I''m with it',4);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I''ll sing it one last time for you Then we really have to go You''ve been the only thing that''s right In all i''ve done.',5);
INSERT loteriadb.frase (frase, idFrase) VALUES ('And I can barely look at you But every single time I do I know we''ll make it anywhere Anywhere from here',6);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Light up, Light up As if you have a choice Even if you cannot hear my voice I''ll be right beside you dear',7);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Louder, louder And we''ll run for our lives I can hardly speak I understand Why you can''t raise your voice to say',8);
INSERT loteriadb.frase (frase, idFrase) VALUES ('To think I might not see those eyes It makes it so hard not to cry And as we say our long goodbyes I nearly do.',9);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Slower, slower We don''t have time for that All I want is to find an easier way To get out of our little heads ',10);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Have heart my dear We''re bound to be afraid Even if it''s just for a few days Making up for all this mess',11);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Autumn leaves we treat as litter People living on a bench Childhood friends who lost contact Fallen soldiers in a trench',12);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Plastic islands in the ocean Violent storms drop atom bombs Hidden women walking slowly Desperate men sing sacred songs',13);
INSERT loteriadb.frase (frase, idFrase) VALUES ('City boy selling countries Surgeons lifting second skin Sitting by software windows Trying to find a virtual friend',14);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I''m not a perfect person There''s many thing I wish I didn''t do But I continue learning I never meant to do those things to you And so I have to say before I go That I just want you to know',15);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I''ve found a reason for me To change who I used to be A reason to start over new And the reason is you',16);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I''m sorry that I hurt you It''s something I must live with everyday And all the pain I put you through I wish I could take it all away And be the one who catches all your tears That''s why I need you to hear',17);
INSERT loteriadb.frase (frase, idFrase) VALUES ('What a mark carved on my heart I was struck by cupid''s darts Hit so fast I did not see Before I knew, love captured me',18);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Every dawn gives way to dusk With each story endings come With the ticking of the clock I long for another touch',19);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Could I have known this fate at all? I did not know I''d get caught up Every sunset brings forth light And soon enough my sun will rise',20);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I was waiting for you to release me I been hanging around for a minute Baby, don''t give me you, it won''t hurt me I don''t even know if you deserve me',21);
INSERT loteriadb.frase (frase, idFrase) VALUES ('But with that moon in the sky Who wants to be alone And when the stars shine so bright Who wants to be alone',22);
INSERT loteriadb.frase (frase, idFrase) VALUES ('But with the timing right It could be paradise To do this now Would not be right',23);
INSERT loteriadb.frase (frase, idFrase) VALUES ('And with the timing right It could be paradise To do this now Would not be right',24);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Can you forgive me again I don''t know what I said But I didn''t mean to hurt you',25);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I heard the words come out I felt that I would die It hurts so much to hurt you',26);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Then you look at me You''re not shouting anymore You''re silently broken',27);
INSERT loteriadb.frase (frase, idFrase) VALUES ('''Cause you were made for me Somehow I''ll make you see How happy you make me, Oh!',28);
INSERT loteriadb.frase (frase, idFrase) VALUES ('And you forgive me again You''re my one true friend And I never meant to hurt you',29);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Dear my love, haven''t you wanted to be with me And dear my love, haven''t you longed to be free',30);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I can''t keep pretending that I don''t even know you And at sweet night, you are my own, take my hand',31);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''re leaving here tonight There''s no need to tell anyone',32);
INSERT loteriadb.frase (frase, idFrase) VALUES ('They''d only hold us down So by the morning light',33);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''ll be half way to anywhere Where love is more than just your name',34);
INSERT loteriadb.frase (frase, idFrase) VALUES ('I have dreamt of a place for you and I No one knows who we are there',35);
INSERT loteriadb.frase (frase, idFrase) VALUES ('All I want is to give my life only to you I''ve dreamt so long I cannot dream anymore Let''s run away, I''ll take you there',36);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''re leaving here tonight There''s no need to tell anyone They''d only hold us down',37);
INSERT loteriadb.frase (frase, idFrase) VALUES ('So by the mornings light We''ll be half way to anywhere Where no one needs a reason',38);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Forget this life, come with me Don''t look back you''re safe now',39);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Unlock your heart, drop your guard No one''s left to stop you',40);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''re leaving here tonight There''s no need to tell anyone',41);
INSERT loteriadb.frase (frase, idFrase) VALUES ('They''d only hold us down So by the morning light',42);
INSERT loteriadb.frase (frase, idFrase) VALUES ('We''ll be half way to anywhere Where love is more than just your name',43);
INSERT loteriadb.frase (frase, idFrase) VALUES ('She was like April sky Sunrise in her eyes Child of light, shining star Fire in her heart',44);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Brightest day, melting snow Breaking through the chill October and April',45);
INSERT loteriadb.frase (frase, idFrase) VALUES ('He was like frozen sky In October night',46);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Darkest cloud endless storm Raining from his heart',47);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Coldest moon, deepest blue Tearing down the spring October and April',48);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Like hate and love World''s apart This fatal love was like poison right from the start',49);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Like light and Dark World''s apart This fatal love was like poison right from the start',50);
INSERT loteriadb.frase (frase, idFrase) VALUES ('Come and share this painting with me Unveiling of me, the magician that never failed',51);
INSERT loteriadb.frase (frase, idFrase) VALUES ('This deep sigh coiled around my chest intoxicated by a major chord I wonder Do I love you or the thought of you?',52);
INSERT loteriadb.frase (frase, idFrase) VALUES ('A crow flew to me Kept its distance Such a proud creation I saw its soul, envied its pride But needed nothing it had',53);
INSERT loteriadb.frase (frase, idFrase) VALUES ('An owl came to me Old and wise Pierced right through my youth I learned its ways, envied its sense But needed nothing it had',54);