INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsr, idDivision, idGradoPosgrado, idGradoActivo, avatar, cargo, area) VALUES ('anjudark89','Flor Nallely', 'Flores', 'Vicente', 'M', 24, 'anjudark@xanum.uam.mx', 'a1b2c3d4e5', 1, 2, null, 1, '/media/img/avatar_default.jpeg', null, null);
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsr, idDivision, idGradoPosgrado, idGradoActivo, avatar, cargo, area) VALUES ('luisa.207310034','Luisa Maria', 'Gomez', 'Leyva', 'M', 24, 'luisa.207310034@xanum.uam.mx', 'a1b2c3d4e5', 1, 2, null, 1, '/media/img/avatar_default.jpeg', null, null);
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsr, idDivision, idGradoPosgrado, idGradoActivo, avatar, cargo, area) VALUES ('jcesarcbi','Julio Cesar', 'Padilla', 'Dorantes', 'H', 28, 'jcesarcbi@xanum.uam.mx', 'a1b2c3d4e5', 1, 2, null, 1, '/media/img/avatar_default.jpeg', null, null);
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsr, idDivision, idGradoPosgrado, idGradoActivo, avatar, cargo, area) VALUES ('guillermotorres','Guillermo', 'Torres', 'Lopez', 'H', 29, 'guillermotorres@xanum.uam.mx', 'a1b2c3d4e5', 1, 2, null, 1, '/media/img/avatar_default.jpeg', null, null);
INSERT INTO loteriadb.usuario (nombreUsr, nombre, aPaterno, aMaterno, sexo, edad, correo, contrasena, idTipoUsr, idDivision, idGradoPosgrado, idGradoActivo, avatar, cargo, area) VALUES ('jezrelmx1304','Efren', 'Valdez', 'Jasso', 'H', 28, 'jezrelmx1304@xanum.uam.mx', 'a1b2c3d4e5', 1, 2, null, 1, '/media/img/avatar_default.jpeg', null, null);

INSERT INTO loteriadb.jugador (usuario_idUsr, juego_idJuego, scoreTotal) VALUES (1,1,6800);
INSERT INTO loteriadb.jugador (usuario_idUsr, juego_idJuego, scoreTotal) VALUES (2,1,6200);
INSERT INTO loteriadb.jugador (usuario_idUsr, juego_idJuego, scoreTotal) VALUES (3,1,8100);
INSERT INTO loteriadb.jugador (usuario_idUsr, juego_idJuego, scoreTotal) VALUES (4,1,14900);
INSERT INTO loteriadb.jugador (usuario_idUsr, juego_idJuego, scoreTotal) VALUES (5,1,13600);